site_name: HarmonyDocs
nav:
    - Installation: 'install.md'
    - Changelog: changelog.md

docs_dir: docs-src
site_dir: docs


theme: 
    name: material
    logo: img/favicon.ico
    favicon: img/favicon.ico
    palette:
        primary: black

copyright: Copyright &copy; 2020 - 2023 Robbert van Renesse

extra:
  generator: false

extra_css:
  - stylesheets/styles.css

markdown_extensions:
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.snippets:
        check_paths: true
        base_path: docs-src/textbook/code
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.superfences

extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js