site_name: HarmonyDocs
nav:
    - Overview: 'index.md'
    - 'Getting Started':
        - 'Introduction': 'guides/introduction.md'
        - 'Installation': 'textbook/install.md'
    - 'Textbook':
        - "On Concurrent Programming": 'textbook/index.md'
        - "Hello World! ": 'textbook/harmonyintro.md'
        - "The Problem of Concurrent Programming ": 'textbook/concurrent.md'
        - "The Harmony Virtual Machine ": 'textbook/harmonymachine.md'
        - "Critical Sections ": 'textbook/critical.md'
        - "Peterson's Algorithm ": 'textbook/peterson.md'
        - "Harmony Methods and Pointers ": 'textbook/method.md'
        - "Specification ": 'textbook/specification.md'
        - "Spinlock ": 'textbook/spinlock.md'
        - "Lock Implementations ": 'textbook/synch.md'
        - "Concurrent Data Structures ": 'textbook/cds.md'
        - "Fine-Grained Locking ": 'textbook/finegrained.md'
        - "Testing ": 'textbook/testing.md'
        - "Debugging ": 'textbook/debugging.md'
        - "Conditional Waiting ": 'textbook/condwait.md'
        - "Split Binary Semaphores ": 'textbook/sbs.md'
        - "Starvation ": 'textbook/starvation.md'
        - "Monitors ": 'textbook/monitors.md'
        - "Deadlock ": 'textbook/deadlock.md'
        - "Actors and Message Passing ": 'textbook/actor.md'
        - "Barrier Synchronization ": 'textbook/barrier.md'
        - "Interrupts ": 'textbook/interrupts.md'
        - "Non-Blocking Synchronization ": 'textbook/nonblocking.md'
        - "Alternating Bit Protocol ": 'textbook/abp.md'
        - "Leader Election ": 'textbook/leader.md'
        - "Transactions and Two Phase Commit ": 'textbook/2pc.md'
        - "Chain Replication ": 'textbook/chain.md'
        - "Replicated Atomic Read/Write Register ": 'textbook/abd.md'
        - "Distributed Consensus ": 'textbook/consensus.md'
        - "Paxos ": 'textbook/paxos.md'
        - "Needham-Schroeder Authentication Protocol ": 'textbook/ns.md'
    - 'Reference':
        - "Harmony Language Details": 'textbook/values.md'
        - "The Harmony Virtual Machine ": 'textbook/hvm.md'
        - "How Harmony Works": 'textbook/howitworks.md'
        - "Harmony Modules": 'textbook/module.md'
    - Changelog: changelog.md
    - "Acknowledgments": 'textbook/acknowledgments.md'

docs_dir: docs-src
site_dir: docs

theme: 
    name: material
    logo: img/favicon.ico
    favicon: img/favicon.ico
    palette:
        primary: black

extra:
  generator: false

markdown_extensions:
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.snippets

extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js