site_name: HarmonyDocs
nav:
    - Overview: 'index.md'
    - 'Getting Started':
        - 'Introduction': 'guides/introduction.md'
        - 'Installation': 'textbook/install.md'
    - 'Textbook':
        - "1 On Concurrent Programming": 'textbook/index.md'
        - "2 Hello World! ": 'textbook/harmonyintro.md'
        - "3 The Problem of Concurrent Programming ": 'textbook/concurrent.md'
        - "4 The Harmony Virtual Machine ": 'textbook/harmonymachine.md'
        - "5 Critical Sections ": 'textbook/critical.md'
        - "6 Peterson's Algorithm ": 'textbook/peterson.md'
        - "7 Harmony Methods and Pointers ": 'textbook/method.md'
        - "8 Specification ": 'textbook/specification.md'
        - "9 Spinlock ": 'textbook/spinlock.md'
        - "10 Lock Implementations ": 'textbook/synch.md'
        - "11 Concurrent Data Structures ": 'textbook/cds.md'
        - "12 Fine-Grained Locking ": 'textbook/finegrained.md'
        - "13 Testing ": 'textbook/testing.md'
        - "14 Debugging ": 'textbook/debugging.md'
        - "15 Conditional Waiting ": 'textbook/condwait.md'
        - "16 Split Binary Semaphores ": 'textbook/sbs.md'
        - "17 Starvation ": 'textbook/starvation.md'
        - "18 Monitors ": 'textbook/monitors.md'
        - "19 Deadlock ": 'textbook/deadlock.md'
        - "20 Actors and Message Passing ": 'textbook/actor.md'
        - "21 Barrier Synchronization ": 'textbook/barrier.md'
        - "22 Interrupts ": 'textbook/interrupts.md'
        - "23 Non-Blocking Synchronization ": 'textbook/nonblocking.md'
        - "24 Alternating Bit Protocol ": 'textbook/abp.md'
        - "25 Leader Election ": 'textbook/leader.md'
        - "26 Transactions and Two Phase Commit ": 'textbook/2pc.md'
        - "27 Chain Replication ": 'textbook/chain.md'
        - "28 Working with Actions ": 'textbook/actions.md'
        - "29 Replicated Atomic Read/Write Register ": 'textbook/abd.md'
        - "30 Distributed Consensus ": 'textbook/consensus.md'
        - "31 Paxos ": 'textbook/paxos.md'
        - "32 Needham-Schroeder Authentication Protocol ": 'textbook/ns.md'
    - 'Reference':
        - 'Using the Command Line': 'textbook/commandline.md'
        - "Harmony Language Details": 'textbook/values.md'
        - "The Harmony Virtual Machine ": 'textbook/hvm.md'
        - "How Harmony Works": 'textbook/howitworks.md'
        - "Simplified Grammar": 'textbook/grammar.md'
        - "Harmony Modules": 'textbook/module.md'
    - Changelog: changelog.md
    - "Acknowledgments": 'textbook/acknowledgments.md'

docs_dir: docs-src
site_dir: docs


theme: 
    name: material
    logo: img/favicon.ico
    favicon: img/favicon.ico
    palette:
        primary: black

copyright: Copyright &copy; 2020 - 2023 Robbert van Renesse

extra:
  generator: false

extra_css:
  - stylesheets/styles.css

markdown_extensions:
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.snippets:
        check_paths: true
        base_path: docs-src/textbook/code
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.superfences

extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js