site_name: HarmonyDocs
nav:
    - Overview: 'index.md'
    - 'Getting Started':
        - 'Introduction': 'guides/introduction.md'
        - 'Installation': 'guides/installation.md'
        - 'Running a program': 'guides/running-harmony.md'
    - 'Textbook':
        - "On Concurrent Programming": 'reference/textbook/index.md'
        - "Hello World! ": 'reference/textbook/harmonyintro.md'
        - "The Problem of Concurrent Programming ": 'reference/textbook/concurrent.md'
        - "The Harmony Virtual Machine ": 'reference/textbook/harmonymachine.md'
        - "Critical Sections ": 'reference/textbook/critical.md'
        - "Peterson's Algorithm ": 'reference/textbook/peterson.md'
        - "Harmony Methods and Pointers ": 'reference/textbook/method.md'
        - "Specification ": 'reference/textbook/specification.md'
        - "Spinlock ": 'reference/textbook/spinlock.md'
        - "Lock Implementations ": 'reference/textbook/synch.md'
        - "Concurrent Data Structures ": 'reference/textbook/cds.md'
        - "Fine-Grained Locking ": 'reference/textbook/finegrained.md'
        - "Testing ": 'reference/textbook/testing.md'
        - "Debugging ": 'reference/textbook/debugging.md'
        - "Conditional Waiting ": 'reference/textbook/condwait.md'
        - "Split Binary Semaphores ": 'reference/textbook/sbs.md'
        - "Starvation ": 'reference/textbook/starvation.md'
        - "Monitors ": 'reference/textbook/monitors.md'
        - "Deadlock ": 'reference/textbook/deadlock.md'
        - "Actors and Message Passing ": 'reference/textbook/actor.md'
        - "Barrier Synchronization ": 'reference/textbook/barrier.md'
        - "Interrupts ": 'reference/textbook/interrupts.md'
        - "Non-Blocking Synchronization ": 'reference/textbook/nonblocking.md'
        - "Alternating Bit Protocol ": 'reference/textbook/abp.md'
        - "Leader Election ": 'reference/textbook/leader.md'
        - "Transactions and Two Phase Commit ": 'reference/textbook/2pc.md'
        - "Chain Replication ": 'reference/textbook/chain.md'
        - "Replicated Atomic Read/Write Register ": 'reference/textbook/abd.md'
        - "Distributed Consensus ": 'reference/textbook/consensus.md'
        - "Paxos ": 'reference/textbook/paxos.md'
        - "Needham-Schroeder Authentication Protocol ": 'reference/textbook/ns.md'
        - "Acknowledgments ": 'reference/textbook/acknowledgments.md'
    - 'Reference':
        - 'Language':
            - "Harmony Language Details": 'reference/textbook/values.md'
            - "The Harmony Virtual Machine ": 'reference/textbook/hvm.md'
            - "How Harmony Works ": 'reference/textbook/howitworks.md'
        - 'Library':
            - 'Overview': 'reference/library/overview.md'
            - 'alloc': 'reference/library/alloc.md'
            - 'bag': 'reference/library/bag.md'
            - 'hoare': 'reference/library/hoare.md'
            - 'list': 'reference/library/list.md'
            - 'set': 'reference/library/set.md'
            - 'synch': 'reference/library/synch.md'
        - 'Textbook': 'reference/textbook.md'
    - Changelog: changelog.md
    - "Acknowledgments": 'reference/textbook/acknowledgments.md'

docs_dir: docs-src
site_dir: docs

theme: 
    name: material
    logo: img/favicon.ico
    favicon: img/favicon.ico
    palette:
        primary: black

extra:
  generator: false

markdown_extensions:
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.snippets

extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js