site_name: HarmonyDocs
nav:
    - Overview: 'index.md'
    - 'Getting Started':
        - 'Introduction': 'guides/introduction.md'
        - 'Installation': 'guides/installation.md'
        - 'Running a program': 'guides/running-harmony.md'
    - 'Reference':
        - 'Language':
            - 'Value Types': 'reference/language/value-types.md'
        - 'Textbook': 'reference/textbook.md'
    - Changelog: changelog.md
theme: readthedocs